### ISSUE TITLE
LAT LONG entry format

### ISSUE THREAD

**Issue by dwillmore** [rsadsb/adsb_deku#115]
I can't find where the format for the latitude and longitude is specified.  I tried following the --help suggestions and the errors produced, but I've gotten nowhere so far.

> willmore@localhost tui]$ ./radar 
> error: The following required arguments were not provided:
>     --lat <LAT>
>     --long <LONG>
> 
> USAGE:
>     radar [OPTIONS] --lat <LAT> --long <LONG>
> 
> For more information try --help
> [willmore@localhost tui]$ ./radar --lat 40.0 --long -80.0
> error: Found argument '-8' which wasn't expected, or isn't valid in this context
> 
> 	If you tried to supply `-8` as a value rather than a flag, use `-- -8`
> 
> USAGE:
>     radar [OPTIONS] --lat <LAT> --long <LONG>
> 
> For more information try --help
> [willmore@localhost tui]$ ./radar --lat 40.0 --long -- -80.0
> error: Found argument '-80.0' which wasn't expected, or isn't valid in this context
> 
> 	If you tried to supply `-80.0` as a value rather than a flag, use `-- -80.0`
> 
> USAGE:
>     radar [OPTIONS] --lat <LAT> --long <LONG>
> 
> For more information try --help

How does it want 40N, 80W specified?

**Comment by wcampbell0x2a** [comment]
Hey!

> I can't find where the format for the latitude and longitude is specified. I tried following the --help suggestions and the errors produced, but I've gotten nowhere so far.
> 
> > willmore@localhost tui]$ ./radar
> > error: The following required arguments were not provided:
> > --lat 
> > --long 
> > USAGE:
> > radar [OPTIONS] --lat  --long 
> > For more information try --help
> > [willmore@localhost tui]$ ./radar --lat 40.0 --long -80.0
> > error: Found argument '-8' which wasn't expected, or isn't valid in this context
> > If you tried to supply `-8` as a value rather than a flag, use `-- -8`
> > USAGE:
> > radar [OPTIONS] --lat  --long 
> > For more information try --help
> > [willmore@localhost tui]$ ./radar --lat 40.0 --long -- -80.0
> > error: Found argument '-80.0' which wasn't expected, or isn't valid in this context
> > If you tried to supply `-80.0` as a value rather than a flag, use `-- -80.0`
> > USAGE:
> > radar [OPTIONS] --lat  --long 
> > For more information try --help
> 
> How does it want 40N, 80W specified?

 In the README.md, I have it described as `--lat="50.0" --long="50.0"`.

**Comment by dwillmore** [comment]
*facepalm*  Yes, the = really makes all the difference.  Pilot error again.
