### ISSUE TITLE
Terminal left in broken state

### ISSUE THREAD

**Issue by dwillmore** [rsadsb/adsb_deku#116]
After exiting from radar, any mouse action in the text terminal from which it was run now disaplay as excape characters.  This persists until the terminal is closed.  ESC c did not clear this conditon.  Seems radar is not restoring the terminal condition upon exit.

**Comment by wcampbell0x2a** [comment]
> After exiting from radar, any mouse action in the text terminal from which it was run now disaplay as excape characters. This persists until the terminal is closed. ESC c did not clear this conditon. Seems radar is not restoring the terminal condition upon exit.

What terminal are you using, I'll test this later.

**Comment by dwillmore** [comment]
Xfce terminal under Fedora 34.  Should behave like a normal xterm in this
context.  Thank you!

**Comment by dwillmore** [comment]
I tried it with the Gnome terminal and got similar results.

**Comment by wcampbell0x2a** [comment]
I can't reproduce this with `gnome-terminal`, did you exit `radar` after a panic or something or were you using `q` or `ctrl+c`?

**Comment by dwillmore** [comment]
I used 'q'.

**Comment by wcampbell0x2a** [comment]
Huh, I've run into what you are talking about randomly. I'll try and reproduce it more..

**Comment by dwillmore** [comment]
Thank you. It is every time for me.  It even happens some times when I get
just the error message.

**Comment by dwillmore** [comment]
I can't build here due to the package requiring a newer version of Rust than Fedora 34 provides.  I can test a binary, but there's no release with this change in it, yet.

**Comment by wcampbell0x2a** [comment]
Sorry about that, I always want to use new features. I usually use `rustup` so that's not a problem.

That being said, you can grab the latest binaries from the CI build like such: https://github.com/rsadsb/adsb_deku/actions/runs/1913359381

**Comment by dwillmore** [comment]
I will try that, thank you.

**Comment by dwillmore** [comment]
I can verify that this fix works. Thank you.  I had to rig up rtl_adsb and netcat because 1090 required a newer version of SoapySDR, but that shouldn't invalidate the testing.  I reproduced the old failure and the new success just to be sure.

Thank you, again!
