### ISSUE TITLE
Include option to switch between ICAO hex and callsign in map view

### ISSUE THREAD

**Issue by dziban303** [rsadsb/adsb_deku#176]
It'd be useful to add a hotkey to switch between display ICAO hex and callsign on the map screen. I think it'd also be helpful to have it display callsign by default without the need to use `--display-callsign` upon launch.

**Comment by wcampbell0x2a** [comment]
> It'd be useful to add a hotkey to switch between display ICAO hex and callsign on the map screen

Use `n` for that.

> I think it'd also be helpful to have it display callsign by default without the need to use --display-callsign upon launch.

I think so also, since all online ADSB show callsigns first.

**Comment by dziban303** [comment]
> Use n for that.

Ah, thanks. Then let me suggest adding the `n` hotkey to the help menu.

![image](https://user-images.githubusercontent.com/7931765/186465374-b0d56342-3315-4ffd-9fd6-b902471c55f9.png)

**Comment by wcampbell0x2a** [comment]
> > Use n for that.
> 
> Ah, thanks. Then let me suggest adding the `n` hotkey to the help menu.

whoops, will do.

**Comment by wcampbell0x2a** [comment]
v0.6.1 fixes this issue.
