### ISSUE TITLE
Publish rsadsb_common, please

### ISSUE THREAD

**Issue by Vincer239** [rsadsb/adsb_deku#197]
https://github.com/rsadsb/adsb_deku/blob/7ef031d0179edfb9ba7da68f8fc61843ae4b8cef/rsadsb_common/README.md?plain=1#L5
Yes, please.. I am currently building an ADS-B system. I get a lot of "different versions of the same crate" errors when using adsb_deku and rsadsb_common at the same time. I believe pulling both from crates.io would resolve the issue.

**Comment by wcampbell0x2a** [comment]
Sure, I'll look into this.

**Comment by wcampbell0x2a** [comment]
Pushed https://crates.io/crates/rsadsb_common, lmk if you have problems.
