### ISSUE TITLE
Possible position mis-decode

### ISSUE THREAD

**Issue by wiseman** [rsadsb/adsb_deku#21]
```
8da353c65881360d90a7bc9b1858
 Extended Squitter Airborne position (barometric altitude)
  Address:       a353c6 (Mode S / ADS-B)
  Air/Ground:    airborne
  Altitude:      24675 ft barometric
  CPR type:      Airborne
  CPR odd flag:  odd
  CPR latitude:  (67272)
  CPR longitude: (42940)
```
```
a353c6: (Position { latitude: 33.64013671875, longitude: -125.04295349121094 }, 22625)
```

But that aircraft was closer to longitude -117 (screenshot may have been a few minutes after the decode above):
![Screen Shot 2021-10-28 at 7 41 38 PM](https://user-images.githubusercontent.com/52466/139365494-fc3363fa-15f2-4ad2-a907-dfd39e7d24ae.png)

**Comment by wcampbell0x2a** [comment]
Can confirm this issue when running Coverage for a night and zooming out:


![2021-11-12-074112_1338x874_scrot](https://user-images.githubusercontent.com/15236002/141469062-d9b30a8f-4aa7-4f11-8f9d-0d891e451b54.png)

**Comment by Jachdich** [comment]
I have something similar to this, fairly often I decode a lat/long of -300 ish by -170 ish, with a receiver location of roughly 50, -5. There's a possibility this is down to interference but I find it odd that it would always be in the ballpark of -300 -170.

**Comment by wcampbell0x2a** [comment]
> I have something similar to this, fairly often I decode a lat/long of -300 ish by -170 ish, with a receiver location of roughly 50, -5. There's a possibility this is down to interference but I find it odd that it would always be in the ballpark of -300 -170.

Interesting. I'd like to get rid of this issue. This would require having more lat/long cpr values for all the bad lat/long values after calling `get_position`.

I'd also like to see if this is a problem in the C libraries, or if they do more pre/post processing.

Which dump1090 did you use?

**Comment by Jachdich** [comment]
> Which dump1090 did you use?

I used [this version](https://github.com/rsadsb/dump1090_rs) of` dump1090_rs`
