### ISSUE TITLE
tracking crates.io new category

### ISSUE THREAD

**Issue by wcampbell0x2a** [rsadsb/adsb_deku#54]
https://github.com/rust-lang/crates.io/issues/4105#issuecomment-962947851

**Comment by elpiel** [comment]
@wcampbell0x2a would you like any additional categories that better reflect this crate?
I can think of a new category `Software defined radio` for example.

**Comment by wcampbell0x2a** [comment]
> @wcampbell0x2a would you like any additional categories that better reflect this crate? I can think of a new category `Software defined radio` for example.

That would be great, I know https://github.com/FutureSDR/FutureSDR might also use that category.
