### ISSUE TITLE
Improve explanation of ADS-B daemon and port configuration in README

### ISSUE THREAD

**Issue by mikemorris** [rsadsb/adsb_deku#60]
I'm trying to get this running, and I'm a little lost at what I'm assuming is a basic configuration issue - I'm using macOS and have an RTL-SDR plugged in and both apps panic with a `ConnectionRefused` error when attempting to `cargo run`, not quite sure how to proceed...

```
thread 'main' panicked at 'Could not open port to ADS-B daemon: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }', apps/src/radar.rs:283:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }', apps/src/1090.rs:35:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by wcampbell0x2a** [comment]
Hey!

First you need what I call a server, something like https://github.com/rsadsb/dump1090_rs if you want this all in rust.

This is in the instructions: https://github.com/rsadsb/adsb_deku#serverdemodulationexternal-applications

second you can connect either `1090` or `radar` from this repo. The example commands from https://github.com/rsadsb/adsb_deku#radar-tui and https://github.com/rsadsb/adsb_deku#1090 should work.

lmk if you have more issues, I haven't had many people other then me run the project and something of a Quick Start guide might be in order.

**Comment by mikemorris** [comment]
Thanks, that helps - I can get both apps running now (although no aircraft detected yet). Definitely didn't make the connection that a separate server app was required on first read.

A quick start guide would definitely be appreciated, including some basic hardware things like what sort of antenna to use.
