### ISSUE TITLE
radar --gpsd flag still requires specifying lat and long?

### ISSUE THREAD

**Issue by mikemorris** [rsadsb/adsb_deku#62]
Reading the description of the `--gpsd` flag in https://github.com/rsadsb/adsb_deku#radar-tui, I'd expect that it would be an alternative to manually specifying `--lat --long`, is it not, or does it require passing a specific gpsd server location as a value?

```
error: The following required arguments were not provided:
    --lat <LAT>
    --long <LONG>
```

Somewhat related, it would be helpful to have a little more context on how any values passed to `--cities` are used - is it to show cities on the map at low zoom levels? Would it maybe be more appropriate for it to be instead named something more generic like `--locations` to display any valid points of interest, such as specific airports?

**Comment by mikemorris** [comment]
Looking more closely at radar app docs, it appears `--gpsd-ip` would be how to specify the server location - is there a separate project that would need to be running locally (on what port?) to provide this service, or is it a common OS package?

**Comment by wcampbell0x2a** [comment]
Normally I give an approximation of my current position with `--lat` and `--long`, and enable `--gpsd` if I am running a gpsd server.

Yes, the gpsd is it's own project and you should be able to find it in your linux package system. https://gpsd.io/

**Comment by wcampbell0x2a** [comment]
The port is usually 2947, although I suppose you could change it in the settings. I host it locally, but if you host it on a raspberry pi with a gps receiver or something on the network you will point it to that location.
