### ISSUE TITLE
No documented way to exit radar app

### ISSUE THREAD

**Issue by mikemorris** [rsadsb/adsb_deku#63]
Documented [key bindings](https://github.com/rsadsb/adsb_deku/tree/master/apps#key-bindings) don't mention any way to exit the tui.rs interface, and ctrl-c doens't seem to do anything, I'm currently only able to exit by closing the terminal window or triggering a crash.

**Comment by wcampbell0x2a** [comment]
Sorry, I never documented that. It's the letter `q`. I intent on adding a help screen, but that hasn't been implemented yet.
